[package]
name = "medeor"
version = "0.1.0"
description = "A friendly local media library and playback tool."
authors = ["Medeor"]
edition = "2021"

[lib]
name = "medeor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
rusqlite = { version = "0.40.2", features = ["bundled"] }
